org: graystrider
app: aws-node-simple-http-endpoint
service: serverless-simple-http-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

package:
  excludeDevDependencies: false

plugins:
  - serverless-webpack
  - serverless-plugin-common-excludes
  - serverless-plugin-package-size
  - serverless-plugin-include-dependencies
  - serverless-offline

custom:
  packageLimit: '1mb'

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

functions:
  currentTime:
    handler: handler.hello
    events:
      - http:
          path: ping
          method: get
