org: graystrider
app: aws-node-simple-http-endpoint
service: serverless-simple-http-endpoint

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-webpack
  - serverless-plugin-common-excludes
  - serverless-plugin-package-size
  - serverless-offline

custom:
  packageLimit: '1mb'

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1

functions:

  currentTime:
    handler: src/handler.hello
    events:
      - http:
          path: ping
          method: get

  botHelloGet:
    handler: src/bot.sayHelloGet
    events:
      - http:
          path: hello
          method: get

  botHelloPost:
    handler: src/bot.sayHelloPost
    events:
      - http:
          path: hello
          method: post

  initializeBot:
    handler: src/bot.initializeBot
    events:
      - http:
          path: initialize
          method: get
